### ISSUE TITLE
SumatraPDF Pre-release version must be 3.2.12118 or later

### ISSUE THREAD

**Issue by GitHubRulesOK** [nod5/HighlightJump#2]
There are many users who still use earlier more stable pre-releases such as 3.2.11133
My current default is still 3.2.12091 and I drop back to 3.2.11133 for some legacy uses
Whilst it is mentioned in notes that it needs to be recent it is not clear that 3.2.12118 (7th Feb 2020) was the earliest pre-release without too many bugs that is compatible with HighlightJump

**Comment by nod5** [comment]
Thanks. Will add to documentation.

Not sure how _best_ to phrase it though. I can write "tested in Prerelease version ____" or some such. But Prerelease versions are replaced quickly in the recent past and there is no archive of older Prerelease version that I know of. And HighlightJumper is of course unavoidably fragile since any new Prerelease/Daily versions might come with changes that break something here downstream. I will add a note about that in the readme too.

**Comment by nod5** [comment]
Readme updated with information and compatibility advice concerning SumatraPDF Prerelease versions
